name: Deploy to Vonage Cloud Runtime

on:
  push:
    branches: [ "main" ]  # run deploy whenever you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cloud Runtime CLI
        run: npm install -g @vonage/cloud-runtime-cli
      - name: Deploy to Vonage
        run: |
          vcr deploy \
            --api-key ${{ secrets.VONAGE_API_KEY }} \
            --api-secret ${{ secrets.VONAGE_API_SECRET }} \
            --region aws.use1
